name: Playwright Tests with Xray Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_plan_key:
        description: 'Jira Test Plan Key (optional)'
        required: false
        type: string
      environment:
        description: 'Test Environment'
        required: false
        default: 'CI/CD'
        type: string

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chrome
    
    - name: Run Playwright tests
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        JIRA_TEST_PLAN_KEY: ${{ github.event.inputs.test_plan_key || '' }}
        JIRA_ENVIRONMENT: ${{ github.event.inputs.environment || 'CI/CD' }}
        JIRA_VERSION: ${{ github.sha }}
        JIRA_REPORTER: GitHub Actions
      run: |
        npx playwright test --project="Google Chrome" --reporter=junit
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results.xml
          test-results/
        retention-days: 30

  xray-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: playwright-report
        path: test-results/
    
    - name: Install dependencies
      run: npm ci
    
    - name: Report to Jira Xray
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        JIRA_TEST_PLAN_KEY: ${{ github.event.inputs.test_plan_key || '' }}
        JIRA_ENVIRONMENT: ${{ github.event.inputs.environment || 'CI/CD' }}
        JIRA_VERSION: ${{ github.sha }}
        JIRA_REPORTER: GitHub Actions
      run: |
        # Run tests with Xray reporter to send results
        npx playwright test --reporter=./xray-reporter-simple.js --project="Google Chrome"

